  employeeid: "employeeid",
  employeelocation: "employeelocation",
  gender: "gender",
  managerid: "managerid",
  managername: "managername",
  manageremail: "manageremail",
  managerphone: "managerphone",
  openapplication: "openapplication",
  //domain: window.location.hostname.split(".").splice(0, 1).join(),
  domainname: domainName,
  // domain: "demo-kovaionbi",
  // domain: "demo-aravind",
  // domain: "demo-balaji",
  // domain: "demo-admin",
  //domain: "demo-whatsappclient",
  //domain: "demo-demohrtest",
  // domain: "demo-subash28",
   domain: "demo-demohrtest",
